# Generated by Django 4.2 on 2023-04-24 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("conversation", "0002_rename_conversationalmessage_conversationmessage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="conversationmessage",
            old_name="craeted_by",
            new_name="created_by",
        ),
    ]
